server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: product-service
        uri:
          lb://PRODUCT-SERVICE
        predicates:
        - Path=/products/**
      - id: price-service
        uri:
          lb://PRICE-SERVICE
        predicates:
        - Path=/prices/**
      - id: inventory-service
        uri:
          lb://INVENTORY-SERVICE
        predicates:
        - Path=/inventory/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
        